config/routes.rb
Rails.application.routes.draw do
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "evaluateds#index"

  resources :evaluateds do
    resources :applied_instruments, only: %i[ index new show create ]
  end

  namespace :evaluations do
    resources :step_one, only: %i[ show update ]
    resources :step_two, only: %i[ show update ]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/applied_instrument.rb
class AppliedInstrument < ApplicationRecord
  belongs_to :evaluated
  belongs_to :instrument

  scope :finished, -> { where finished: true }

  POINTS_MAPPING = { 1 => 3, 2 => 2, 3 => 1, 4 => 0 }

  def result
    point_for_answer_1 + point_for_answer_2 + point_for_answer_3 + point_for_answer_4 + point_for_answer_5
  end

  private
    def point_for_answer_1
      POINTS_MAPPING[answer_1] || 0
    end

    def point_for_answer_2
      POINTS_MAPPING[answer_2] || 0
    end

    def point_for_answer_3
      POINTS_MAPPING[answer_3] || 0
    end

    def point_for_answer_4
      POINTS_MAPPING[answer_4] || 0
    end

    def point_for_answer_5
      POINTS_MAPPING[answer_5] || 0
    end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/evaluated.rb
class Evaluated < ApplicationRecord
  belongs_to :psychologist
  has_many :applied_instruments, dependent: :destroy
end

app/models/instrument.rb
class Instrument < ApplicationRecord
end

app/models/psychologist.rb
class Psychologist < ApplicationRecord
  has_many :evaluateds, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  private
    def authenticate
      if psychologist = authenticate_with_http_basic { |user_name, _| Psychologist.find_by(user_name: user_name) }
        Current.user = psychologist
      else
        request_http_basic_authentication
      end
    end
end

app/controllers/applied_instruments_controller.rb
class AppliedInstrumentsController < ApplicationController
  include EvaluatedScoped

  def index
    @applied_instruments = @evaluated.applied_instruments
  end

  def show
    @applied_instrument = @evaluated.applied_instruments.finished.find(params[:id])
  end

  def new
    @applied_instrument = AppliedInstrument.new
  end

  def create
     @applied_instrument = @evaluated.applied_instruments.create!(applied_instrument_params)
     send_applied_instrument_invitation

     redirect_to evaluated_applied_instruments_url(@evaluated), notice: "Instrumento aplicado com sucesso."
  end

  private

    def applied_instrument_params
      params.require(:applied_instrument).permit(:instrument_id)
    end

    def send_applied_instrument_invitation
      AppliedInstrumentMailer.with(applied_instrument: @applied_instrument).invitation.deliver_later
    end
end

app/controllers/concerns/evaluated_scoped.rb
module EvaluatedScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_evaluated
  end

  private
    def set_evaluated
      @evaluated = Current.user.evaluateds.find(params[:evaluated_id])
    end
end

app/controllers/concerns/evaluation_scoped.rb
module EvaluationScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_applied_instrument
  end

  private
    def set_applied_instrument
      @applied_instrument = AppliedInstrument.find_signed!(params[:id])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      head :not_found
    end
end

app/controllers/evaluateds_controller.rb
class EvaluatedsController < ApplicationController
  before_action :set_evaluated, only: %i[ show edit update destroy ]

  def index
    @evaluateds = Current.user.evaluateds.all
  end

  def show
  end

  def new
    @evaluated = Evaluated.new
  end

  def edit
  end

  def create
    @evaluated = Current.user.evaluateds.create!(evaluated_params)
    redirect_to @evaluated, notice: "Avaliado criado com sucesso."
  end

  def update
    @evaluated.update! evaluated_params
    redirect_to @evaluated, notice: "Avaliado alterado com sucesso.", status: :see_other
  end

  def destroy
    @evaluated.destroy!
    redirect_to evaluateds_url, notice: "Avaliado apagado com sucesso.", status: :see_other
  end

  private
    
    def set_evaluated
      @evaluated = Current.user.evaluateds.find(params[:id])
    end

    def evaluated_params
      params.require(:evaluated).permit(:name, :cpf, :email, :birthdate)
    end
end

app/controllers/evaluations/step_one_controller.rb
class Evaluations::StepOneController < ApplicationController
  include EvaluationScoped

  skip_before_action :authenticate

  def show
  end

  def update
    @applied_instrument.evaluated.update!(evaluated_params)
    redirect_to evaluations_step_two_path(@applied_instrument.signed_id)
  end

  private
    def evaluated_params
      params.require(:evaluated).permit(:name, :cpf, :email, :birthdate)
    end
end

app/controllers/evaluations/step_two_controller.rb
class Evaluations::StepTwoController < ApplicationController
  include EvaluationScoped

  skip_before_action :authenticate

  def show
  end

  def update
    @applied_instrument.update! applied_instrument_params
    @applied_instrument.update! finished: true
    redirect_to evaluations_step_two_path(@applied_instrument.signed_id), notice: "Avaliação finalizada com sucesso."
  end

   private
    def applied_instrument_params
      params.require(:applied_instrument).permit(:answer_1, :answer_2, :answer_3, :answer_4)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluateds_helper.rb
module EvaluatedsHelper
end

app/views/applied_instruments/index.html.erb
<h1>Instrumentos Aplicados</h1>

<div id="applied_instruments">
  <% @applied_instruments.each do |applied_instrument| %>
    <p>
        <strong>Instrumento:</strong><%= link_to_if(applied_instrument.finished?, "#{applied_instrument.instrument.name} - #{l(applied_instrument.created_at, format: :long)}", [@evaluated, applied_instrument]) %>
    </p>
  <% end %>
</div>

<div>
  <%= link_to "Voltar para avaliado #{@evaluated.name}", evaluated_path(@evaluated) %>
</div>

app/views/applied_instruments/new.html.erb
<h1>Aplicar Instrumento</h1>

<%= form_with(model: [@evaluated, @applied_instrument]) do |form| %>
  <div>
    <%= form.label :instrument_id, "Selecione um instrumento"%>
    <%= form.collection_select :instrument_id, Instrument.all, :id, :name, { prompt: "Escolha um instrumento" }, required: true %>
  </div>

  <div>
    <%= form.submit "Aplicar" %>
  </div>
<% end %>

<div>
  <%= link_to "Voltar para avaliado #{@evaluated.name}", evaluated_path(@evaluated) %>
</div>

app/views/applied_instruments/show.html.erb
<div id="<%= dom_id @applied_instrument %>">
  <h1> <%= @applied_instrument.instrument.name %></h1>
  
    <% (1..5).each do |i| %>
      <p>
        <strong>Pergunta <%= i %>:</strong> <%= @applied_instrument.instrument.send("question_#{i}") %>
      </p>
      
      <p>
        <strong>Resposta <%= i %>:</strong> Número <%= @applied_instrument.send("answer_#{i}") %>
      </p>
    <% end %>
  
  <p><strong>Resultado:</strong> <%= @applied_instrument.result %> pontos.</p>
</div>

<div>
  <%= link_to "Voltar para instrumentos aplicados", evaluated_applied_instruments_path(@evaluated) %>
</div>

app/views/evaluateds/_evaluated.html.erb
<div id="<%= dom_id evaluated %>">
  <p>
    <strong>Nome:</strong>
    <%= evaluated.name %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= evaluated.cpf %>
  </p>

  <p>
    <strong>E-mail:</strong>
    <%= evaluated.email %>
  </p>

  <p>
    <strong>Data de Nascimento:</strong>
    <%= evaluated.birthdate %>
  </p>

</div>

app/views/evaluateds/_form.html.erb
<%= form_with(model: evaluated) do |form| %>

  <div>
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :cpf, "CPF", style: "display: block" %>
    <%= form.text_field :cpf, required: true %>
  </div>

  <div>
    <%= form.label :email, "E-mail", style: "display: block" %>
    <%= form.email_field :email, required: true %>
  </div>

  <div>
    <%= form.label :birthdate, "Data de nascimento", style: "display: block" %>
    <%= form.date_field :birthdate, required: true %>
  </div>

  <div>
    <%= form.submit "Salvar" %>
  </div>
  
<% end %>

app/views/evaluateds/edit.html.erb
<h1>Alterando avaliado</h1>

<%= render "form", evaluated: @evaluated %>

<br>

<div>
  <%= link_to "Mostrar este avaliado", @evaluated %> |
  <%= link_to "Voltar para avaliados", evaluateds_path %>
</div>

app/views/evaluateds/index.html.erb
<h1>Avaliados</h1>

<div id="evaluateds">
  <% @evaluateds.each do |evaluated| %>
    <%= render evaluated %>
    <p>
      <%= link_to "Mostrar este avaliado", evaluated %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "Novo avaliado", new_evaluated_path %>

app/views/evaluateds/new.html.erb
<h1>Novo avaliado</h1>

<%= render "form", evaluated: @evaluated %>

<br>

<div>
  <%= link_to "Voltar para avaliados", evaluateds_path %>
</div>

app/views/evaluateds/show.html.erb
<%= render @evaluated %>

<div>
  <%= link_to "Listar instrumentos applicados", evaluated_applied_instruments_path(@evaluated) %> | 
  <%= link_to "Aplicar instrumento", new_evaluated_applied_instrument_path(@evaluated) %>
  <%= link_to "Alterar este avaliado", edit_evaluated_path(@evaluated) %> | 
  <%= button_to "Apagar avaliado", @evaluated, method: :delete %>
  <%= link_to "Voltar para avaliados", evaluateds_path %>
</div>

app/views/evaluations/step_one/show.html.erb
<h1>Questionário</h1>

<%= form_with(model: @applied_instrument.evaluated, url: evaluations_step_one_path(@applied_instrument.signed_id)) do |form| %>

  <div>
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :cpf, "CPF", style: "display: block" %>
    <%= form.text_field :cpf, required: true %>
  </div>

  <div>
    <%= form.label :email, "E-mail", style: "display: block" %>
    <%= form.email_field :email, required: true %>
  </div>

  <div>
    <%= form.label :birthdate, "Data de nascimento", style: "display: block" %>
    <%= form.date_field :birthdate, required: true %>
  </div>

  <div>
    <%= form.submit "Proximo →" %>
  </div>

<% end %>

app/views/evaluations/step_two/show.html.erb
<h1>Avaliação</h1>

<%= form_with(model: @applied_instrument, url: evaluations_step_two_path(@applied_instrument.signed_id)) do |form| %>
  <% if @applied_instrument.instrument.question_1.present? %>
    <div>
      <p><strong> <%= @applied_instrument.instrument.question_1 %></strong><p>
       <%= form.collection_radio_buttons :answer_1, 1..4, :itself, :itself, {}, { required: true } %>
    </div>
  <% end %>

  <% if @applied_instrument.instrument.question_2.present? %>
    <div>
      <p><strong> <%= @applied_instrument.instrument.question_2 %></strong><p>
      <%= form.collection_radio_buttons :answer_2, 1..4, :itself, :itself, {}, { required: true } %>
    </div>
  <% end %>

  <% if @applied_instrument.instrument.question_3.present? %>
    <div>
      <p><strong> <%= @applied_instrument.instrument.question_3 %></strong><p>
      <%= form.collection_radio_buttons :answer_3, 1..4, :itself, :itself, {}, { required: true } %>
    </div>
  <% end %>

  <% if @applied_instrument.instrument.question_4.present? %>
    <div>
      <p><strong> <%= @applied_instrument.instrument.question_4 %></strong><p>
      <%= form.collection_radio_buttons :answer_4, 1..4, :itself, :itself, {}, { required: true } %>
    </div>
  <% end %>

  <% if @applied_instrument.instrument.question_5.present? %>
    <div>
      <p><strong> <%= @applied_instrument.instrument.question_5 %></strong><p>
      <%= form.collection_radio_buttons :answer_5, 1..4, :itself, :itself, {}, { required: true } %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Finalizar" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Editora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash_message = notice || alert %>
      <p class="notice"><%= flash_message %></p>
    <% end %>

    <%= yield %>
  </body>
</html>